<?php
declare(strict_types=1);
require_once __DIR__ . '/bootstrap.php';

$pdo=gaeks_db();$input=$_SERVER['REQUEST_METHOD']==='POST'?gaeks_input(8388608):[];$action=(string)($_GET['action']??$input['action']??'list');
if($action==='public'){
    $token=trim((string)($_GET['token']??'')); if(!preg_match('/^[a-f0-9]{48}$/',$token))gaeks_error('not_found','Link presentasi tidak ditemukan.',404);
    $s=$pdo->prepare('SELECT p.* FROM presentation_shares ps JOIN presentations p ON p.id=ps.presentation_id WHERE ps.public_token=:token AND ps.revoked_at IS NULL AND p.deleted_at IS NULL LIMIT 1');$s->execute([':token'=>$token]);$r=$s->fetch();if(!$r)gaeks_error('not_found','Link presentasi tidak ditemukan.',404);
    $viewer=gaeks_current_user(false);$isOwner=$viewer&&hash_equals((string)$r['user_id'],(string)$viewer['id']);$data=pres_result($r,true);if(!$isOwner)foreach($data['slides']??[] as &$slide){unset($slide['momNote']);}unset($slide);gaeks_ok(['presentation'=>$data,'viewOnly'=>!$isOwner,'isOwner'=>$isOwner]);
}
$user=gaeks_current_user();$uid=(string)$user['id'];if($_SERVER['REQUEST_METHOD']==='POST')gaeks_require_csrf($user);
function pres_id(string $id): string { if(!preg_match('/^[A-Za-z0-9_-]{1,36}$/',$id))gaeks_error('invalid_id','ID presentasi tidak valid.',422);return $id; }
function pres_ms(?string $v): ?int { return $v?strtotime($v)*1000:null; }
function pres_result(array $r,bool $detail=false): array { $data=$detail?(json_decode((string)$r['data_json'],true)?:[]):[];$data['id']=$r['id'];$data['meetingName']=$r['name'];$data['name']=$r['name'];$data['meetingDate']=$r['meeting_date'];$data['date']=$r['meeting_date'];$data['status']=$r['deleted_at']?'trashed':'active';$data['version']=(int)$r['version'];$data['updatedAt']=pres_ms($r['updated_at']);$data['deletedAt']=pres_ms($r['deleted_at']);return $data; }

if($action==='list'){$s=$pdo->prepare('SELECT * FROM presentations WHERE user_id=:uid ORDER BY updated_at DESC');$s->execute([':uid'=>$uid]);gaeks_ok(array_map(static fn($r)=>pres_result($r,false),$s->fetchAll()));}
if($action==='get'){$id=pres_id((string)($_GET['id']??$input['id']??''));$s=$pdo->prepare('SELECT * FROM presentations WHERE id=:id AND user_id=:uid LIMIT 1');$s->execute([':id'=>$id,':uid'=>$uid]);$r=$s->fetch();if(!$r)gaeks_error('not_found','Presentasi tidak ditemukan.',404);gaeks_ok(pres_result($r,true));}
if($action==='share'){$id=pres_id((string)($input['id']??''));$s=$pdo->prepare('SELECT id FROM presentations WHERE id=:id AND user_id=:uid AND deleted_at IS NULL');$s->execute([':id'=>$id,':uid'=>$uid]);if(!$s->fetch())gaeks_error('not_found','Presentasi tidak ditemukan.',404);$token=bin2hex(random_bytes(24));$pdo->prepare('INSERT INTO presentation_shares (presentation_id,owner_user_id,public_token,revoked_at) VALUES (:id,:uid,:token,NULL) ON DUPLICATE KEY UPDATE public_token=VALUES(public_token),revoked_at=NULL')->execute([':id'=>$id,':uid'=>$uid,':token'=>$token]);gaeks_audit($pdo,$uid,'presentation.shared','presentation',$id);gaeks_ok(['url'=>APP_URL.'/presentation-view.html?token='.$token]);}
if($action==='unshare'){$id=pres_id((string)($input['id']??''));$pdo->prepare('UPDATE presentation_shares SET revoked_at=UTC_TIMESTAMP() WHERE presentation_id=:id AND owner_user_id=:uid')->execute([':id'=>$id,':uid'=>$uid]);gaeks_ok(null,200,'Link publik dinonaktifkan.');}

if($action==='save'){
    $pres=$input['data']??$input;$id=!empty($pres['id'])?pres_id((string)$pres['id']):gaeks_uuid();$name=trim((string)($pres['meetingName']??$pres['name']??'Presentasi Baru'));if($name==='')$name='Presentasi Baru';$name=substr($name,0,255);$date=(string)($pres['meetingDate']??$pres['date']??date('Y-m-d'));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))$date=date('Y-m-d');$pres['id']=$id;$pres['meetingName']=$name;$pres['meetingDate']=$date;$json=json_encode($pres,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE);
    $pdo->beginTransaction();try{$s=$pdo->prepare('SELECT * FROM presentations WHERE id=:id'.(gaeks_is_sqlite($pdo)?'':' FOR UPDATE'));$s->execute([':id'=>$id]);$old=$s->fetch();if($old&&$old['user_id']!==$uid){$pdo->rollBack();gaeks_error('not_found','Presentasi tidak ditemukan.',404);}if($old){$expected=isset($pres['version'])?(int)$pres['version']:null;if($expected!==null&&$expected!==(int)$old['version']){$pdo->rollBack();gaeks_error('version_conflict','Presentasi telah berubah di perangkat lain.',409);}$revisionSql=(gaeks_is_sqlite($pdo)?'INSERT OR IGNORE':'INSERT IGNORE')." INTO document_revisions (id,document_type,document_id,user_id,version,data_json) VALUES (:rid,'presentation',:doc,:uid,:version,:data)";$pdo->prepare($revisionSql)->execute([':rid'=>gaeks_uuid(),':doc'=>$id,':uid'=>$uid,':version'=>$old['version'],':data'=>$old['data_json']]);$pdo->prepare('UPDATE presentations SET name=:name,meeting_date=:date,data_json=:data,version=version+1,deleted_at=NULL WHERE id=:id AND user_id=:uid')->execute([':name'=>$name,':date'=>$date,':data'=>$json,':id'=>$id,':uid'=>$uid]);}else{$pdo->prepare('INSERT INTO presentations (id,user_id,name,meeting_date,data_json) VALUES (:id,:uid,:name,:date,:data)')->execute([':id'=>$id,':uid'=>$uid,':name'=>$name,':date'=>$date,':data'=>$json]);}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    $s=$pdo->prepare('SELECT * FROM presentations WHERE id=:id AND user_id=:uid');$s->execute([':id'=>$id,':uid'=>$uid]);gaeks_audit($pdo,$uid,'presentation.saved','presentation',$id);gaeks_ok(pres_result($s->fetch(),true),$old?200:201,'Presentasi tersimpan di server.');
}

if($action==='status'){
    $id=pres_id((string)($input['id']??$_GET['id']??''));$status=(string)($input['status']??$_GET['status']??'trashed');if(!in_array($status,['active','trashed','delete_permanent'],true))gaeks_error('invalid_status','Status tidak valid.',422);$s=$pdo->prepare('SELECT id FROM presentations WHERE id=:id AND user_id=:uid');$s->execute([':id'=>$id,':uid'=>$uid]);if(!$s->fetch())gaeks_error('not_found','Presentasi tidak ditemukan.',404);
    if($status==='delete_permanent'){$pdo->beginTransaction();try{$pdo->prepare("DELETE FROM document_revisions WHERE document_type='presentation' AND document_id=:id AND user_id=:uid")->execute([':id'=>$id,':uid'=>$uid]);$pdo->prepare('DELETE FROM presentations WHERE id=:id AND user_id=:uid')->execute([':id'=>$id,':uid'=>$uid]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
    elseif($status==='trashed')$pdo->prepare('UPDATE presentations SET deleted_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=:id AND user_id=:uid')->execute([':id'=>$id,':uid'=>$uid]);else $pdo->prepare('UPDATE presentations SET deleted_at=NULL,updated_at=UTC_TIMESTAMP() WHERE id=:id AND user_id=:uid')->execute([':id'=>$id,':uid'=>$uid]);gaeks_audit($pdo,$uid,'presentation.'.$status,'presentation',$id);gaeks_ok(null,200,'Status presentasi diperbarui.');
}
gaeks_error('unknown_action','Aksi presentasi tidak dikenal.',404);
